{% set name = "SQLAlchemy-Utc" %}
{% set version = "0.11.0" %}
{% set sha256 = "abcc08a48b7f789e23c5ebe0d67fa15a6da333f4d6d0486e7feed7dc511cfc5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spoqa/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sqlalchemy

test:
  imports:
    - sqlalchemy_utc

about:
  home: https://github.com/spoqa/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SQLAlchemy type to store aware datetime values '
  description: |
    This package provides a drop-in replacement of SQLAlchemy's built-in
    DateTime type with timezone=True option enabled. Although SQLAlchemy's
    built-in DateTime type provides timezone=True option, since some vendors
    like SQLite and MySQL don't provide timestamptz data type, the option
    doesn't make any effect on these vendors.

extra:
  recipe-maintainers:
    - igortg
