travis:
  secure:
    BINSTAR_TOKEN: X538hUM7IdqnYRYtFN35nhYhTJLD+wJbdyVBqc09dibe4tpVMqkt7OSl+h0GxRTYwWlL91sL4lmykeB5WQkEEFgrFhDLOW8/jc5kA2jn5xHTp4qm5Wxxx1BAIm5J+4HYA7E5TVZvgIlmrMkawW9dNIT2/2/GdoNGe+i+MQMaNZtfrFBg/z897ldg8FRJ2zblPgHmYeTyjBVtcoOQKyqFss1XwqAJuo6GfB4183fBxu3R03F28ouGXzo7uhoXfhbpjI+ZMPNCtRQbIhC+NgDg5zP3jRfiBybrtDrlP0sQKAW+XuIYF4gap5PaX1HyAHyuwFDZ/wRKyM+A630i8e9mVsGy+9g4IR4E33OefOePTJtwVGyQekpm97V+frOQ4+sX1udKLgZhJP7Kx55qASrTwF1gVHDC6ilK9SkQC97EdFzysUgUc+SrQyIx6Hk4lWlhpU6gCmaoMk64aQTGmPGkE1ytyXlYTcfveAlRqprrUWJ2y+KiSbwN5av39CbKzaHNoLI1dmzNQKd+mk+hHORvRtCFytM4x3qE4TjNLTjwFrSoKFNinFK3wYFxJZUQJnNmYYiqvIjdQwToohf4lE9mMT6JiVNMdoe1LFFYtXbFUvp3yN/iAbVdiNh8oeO78K+se9wMYUCF8cF9necgpmgU+bqiVcMMuTvJ/sJHeQPo66A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
