travis:
  secure:
    BINSTAR_TOKEN: e3Wvsvc3oRk0UoPUAruacPl/P8PBsKGAZU3bQcGoa7GuKgn/HPBTZHRicU3tbLF7LzL2e09LTUH5b/QRfSepOQnvKKJVxVK+0p9M8foMohMEuB/soOFxwHvuQuOMwr94nP25Eb2dWZN3yqm2BdaOvicRjp7WpITF6hm0Wed2MU/OBLCEy8UGhOPr4XvgvUzM//5+KcHbRIxovfu6YxbQ6VpaLRpaDMIH+oHx1jupOGcFVJU/JCEsuH5/idaYowZM1+bZXVWKOAle6/srckKHUDRPckbpsycbjOz8/AqhVrPFXsaOwd+8Tr202NrQoHVwXOVcvJXeetPODkVf8Cf0kc7dPYMm66WKRwWz3A6RtB8wVz7UXW/0HBZpv76l28a7mia0JCSm/ea9T0VmSn75E6nnKR6tTin9kYiYPfUwheS6UvhR6otFczCmmv7utdESNdZMHh8WDmvoqm2AknIs3VtpwR+aIDQlpbme1pA+S1cxr5bsyyxaTLvO863zH+Mp2AuTZmPYoYg6erh3W6r/lmDoxbtH3hIr2L8VveoywGScI93bwBi8z4BKecg3cTXcV9fLxNI3jKy/3m0BpC7BlHVz6LoWVBiHngRRD4KQyRdm9/o1bkCErZXizzUPHfmffEJItrgIpuSsZbDoKQaSOGl2ks43JZnnTv2tILNNePo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
